# Generated by Django 4.2.10 on 2024-02-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0002_masterproducts_userorders_usercart"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fb_doc_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
